haproxy_globals:
  logs:
    - /dev/log    local0
    - /dev/log    local1 notice
  chroot: /var/lib/haproxy
  stats:
    - key: socket
      value: /run/haproxy/admin.sock mode 660 level admin
    - key: timeout
      value: 30s
  user: haproxy
  group: haproxy
  daemon: true
  ca_base: /etc/ssl/certs
  crt_base: /etc/ssl/private
  ssl_default_bind:
    - key: ciphers
      value: ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    - key: options
      value: no-sslv3
  maxconn: 2048
  tune_ssl:
    - name: default-dh-param
      value: 2048